##### Inporting Lybraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime

##### Importing Dataset

In [ ]:
# Importing data and dropping null values

df = pd.read_excel('Online%20Retail.xlsx')
df = df.dropna(subset=['CustomerID', 'Description'])
df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] > 0]
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [27]:
# calculate key matrics
# creating new column called 'Total_revenue'
df['Total_revenue'] = df['Quantity'] * df['UnitPrice']

In [ ]:
product_performance = df.groupby(['StockCode', 'Description']).agg({
    'Total_revenue': 'sum',
    'Quantity': 'sum',
    'InvoiceNo': 'nunique', # number of transactions
    'InvoiceDate': ['min', 'max'] # first and last sales
}).reset_index()

# Flatten column names

product_performance.columns = ['StockCode', 'Description', 'Total_revenue', 'Total_Quantity', 'Num_Transactions', 'First_Sale_Date', 'Last_Sale_Date']
product_performance.head()

,StockCode,Description,Total_revenue,Total_Quantity,Num_Transactions,First_Sale_Date,Last_Sale_Date
0,10002,INFLATABLE POLITICAL GLOBE,699.55,823,49,2010-12-01 08:45:00,2011-04-18 12:56:00
1,10080,GROOVY CACTUS INFLATABLE,114.41,291,21,2011-02-27 13:47:00,2011-11-21 17:04:00
2,10120,DOGGY RUBBER,40.53,193,29,2010-12-03 11:19:00,2011-12-04 13:15:00
3,10125,MINI FUNKY DESIGN TAPES,930.30,1226,61,2010-12-01 12:23:00,2011-12-09 10:13:00
4,10133,COLOURING PENCILS BROWN TUBE,1143.61,2384,122,2010-12-01 12:15:00,2011-09-07 10:07:00

In [ ]:
# calculate sales velocity (Unit per day)

product_performance['Days_activity'] = (pd.to_datetime(product_performance['Last_Sales_Date']) - pd.to_datetime(products_performance['First_Sale_Date'])).dt.days + 1