## <strong> Data Exploration </strong>

<strong> This python file is written to explore and explian the different column properties of each file records<strong>

##### Exploring the data:
- account.csv :- Holds detail information about the companies description
- dictionary.csv :- Holds the explanation about each csv file columns
- products.csv :- Hold information about the companies products and detail descriptions
- sales_pipeline.csv :- Holds the detail about products sold,  the companies, sales_agent and engagment_date

In [1]:
import pandas as pd
import glob
import numpy as np

In [2]:
account = pd.read_csv('accounts.csv')
print(account.info())
account.head()

<class 'pandas.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     str
 1   sector            85 non-null     str
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     str
 6   subsidiary_of     15 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 4.8 KB
None

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN

In [3]:
dictionary = pd.read_csv('data_dictionary.csv')
print(dictionary.info())
dictionary.head(30)

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Table        21 non-null     str
 1   Field        21 non-null     str
 2   Description  21 non-null     str
dtypes: str(3)
memory usage: 636.0 bytes
None

,Table,Field,Description
0,accounts,account,Company name
1,accounts,sector,Industry
2,accounts,year_established,Year Established
3,accounts,revenue,Annual revenue (in millions of USD)
4,accounts,employees,Number of employees
5,accounts,office_location,Headquarters
6,accounts,subsidiary_of,Parent company
7,products,product,Product name
8,products,series,Product series
9,products,sales_price,Suggested retail price
10,sales_teams,sales_agent,Sales agent
11,sales_teams,manager,Respective sales manager
12,sales_teams,regional_office,Regional office
13,sales_pipeline,opportunity_id,Unique identifier
14,sales_pipeline,sales_agent,Sales agent
15,sales_pipeline,product,Product name
16,sales_pipeline,account,Company name
17,sales_pipeline,deal_stage,Sales pipeline stage (Prospecting > Engaging >...
18,sales_pipeline,engage_date,"Date in which the ""Engaging"" deal stage was in..."
19,sales_pipeline,close_date,"Date in which the deal was ""Won"" or ""Lost"""
20,sales_pipeline,close_value,Revenue from the deal

In [7]:
products = pd.read_csv('products.csv')
print(products.info())
products.head(20)

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      7 non-null      str
 1   series       7 non-null      str
 2   sales_price  7 non-null      int64
dtypes: int64(1), str(2)
memory usage: 300.0 bytes
None

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

In [5]:
sales_pipeline = pd.read_csv('sales_pipeline.csv')
print(sales_pipeline.info())
sales_pipeline.head()

<class 'pandas.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   str
 1   sales_agent     8800 non-null   str
 2   product         8800 non-null   str
 3   account         7375 non-null   str
 4   deal_stage      8800 non-null   str
 5   engage_date     8300 non-null   str
 6   close_date      6711 non-null   str
 7   close_value     6711 non-null   float64
dtypes: float64(1), str(7)
memory usage: 550.1 KB
None

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

In [6]:
sales_team = pd.read_csv('sales_teams.csv')
print(sales_team.info())

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     str
 1   manager          35 non-null     str
 2   regional_office  35 non-null     str
dtypes: str(3)
memory usage: 972.0 bytes
None

<STRONG>>>>>>>.....................NEXT STAGE DATA EXPLORING AND EXPORTING IN PYTHON  .........................<<<<<<</STRONG>