<strong>IMPORTING LYBRARY FOR MERGIN, IMPORTING AND EXPORTING</strong>

In [5]:
import pandas as pd
import glob
import numpy as np
from sqlalchemy import create_engine

<STRONG>INMPORTING AND READING REQUIRED FILES</STRONG>

In [6]:
account = pd.read_csv('accounts.csv')
products = pd.read_csv('products.csv')
sales_pipeline = pd.read_csv('sales_pipeline.csv')
sales_teams = pd.read_csv('sales_teams.csv')

<STRONG>MERGING CSV FILES</STRONG>

In [7]:
file = pd.merge(sales_pipeline, account, on='account', how='left').merge(products, on='product', how='left').merge(sales_teams, on='sales_agent', how='left')
file = pd.DataFrame(file)
file.head()

file.to_csv('hubspot_merge_file.csv')

<STRONG>EXPLRING DATA BEFORE CLEANING</STRONG>

In [8]:
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   opportunity_id    8800 non-null   str
 1   sales_agent       8800 non-null   str
 2   product           8800 non-null   str
 3   account           7375 non-null   str
 4   deal_stage        8800 non-null   str
 5   engage_date       8300 non-null   str
 6   close_date        6711 non-null   str
 7   close_value       6711 non-null   float64
 8   sector            7375 non-null   str
 9   year_established  7375 non-null   float64
 10  revenue           7375 non-null   float64
 11  employees         7375 non-null   float64
 12  office_location   7375 non-null   str
 13  subsidiary_of     1292 non-null   str
 14  series            7320 non-null   str
 15  sales_price       7320 non-null   float64
 16  manager           8800 non-null   str
 17  regional_office   8800 non-null   str
dtypes: float64(5), str(13)
memory usage: 1.2 MB

In [9]:
file.describe()

,close_value,year_established,revenue,employees,sales_price
count,6711.000000,7375.000000,7375.000000,7375.000000,7320.000000
mean,1490.915512,1995.483661,2467.515536,5701.213424,1885.394126
std,2320.670773,9.187126,2596.135671,6816.683924,2619.399523
min,0.000000,1979.000000,4.540000,9.000000,55.000000
25%,0.000000,1988.000000,647.180000,1238.000000,550.000000
50%,472.000000,1995.000000,1698.200000,3492.000000,1096.000000
75%,3225.000000,2002.000000,2952.730000,7523.000000,3393.000000
max,30288.000000,2017.000000,11698.030000,34288.000000,26768.000000

In [10]:
file.select_dtypes('str').describe()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,sector,office_location,subsidiary_of,series,manager,regional_office
count,8800,8800,8800,7375,8800,8300,6711,7375,7375,1292,7320,8800,8800
unique,8800,30,7,85,4,421,306,10,15,7,3,6,3
top,1C1I7A6R,Darcel Schlecht,GTX Basic,Hottechi,Won,2017-07-22,2017-05-22,retail,United States,Acme Corporation,GTX,Melvin Marxen,Central
freq,1,747,1866,200,4238,66,41,1397,6120,322,4217,1929,3512

<STRONG>CREATING FUNCTION FOR CLEANING,RENAMING,D_TYPE CONVERTING AND DROPPING COLUMNS </STRONG>

In [20]:
def data_cleaning(df):
    # read the csv file
    df = pd.read_csv(df)

    # drop the subsidiary_of column
    drop_col = df.drop(columns = ['subsidiary_of'], inplace = True)

    # rename the columns
    df = df.rename(columns = {'account':'company_name'.capitalize(),
                              'revenue':'revenue'.capitalize(),
                              'employees':'employees'.capitalize(),
                              'office_location':'office'.capitalize(),
                              'product':'product_name'.capitalize(),
                              'series':'product_series'.capitalize(),
                              'sales_price':'sales_price'.capitalize(),
                              'opportunity_id':'id'.upper(),
                              'close_value':'close_value'.capitalize(),
                              'close_date':'close_date'.capitalize(),
                              'engage_date':'engage_date'.capitalize(),
                              'sales_agent':'sales_agent'.capitalize(), 
                              'deal_stage':'deal_stage'.capitalize(),
                              'year_established':'year_established'.capitalize(),
                              'regional_office':'regional_office'.capitalize()})
    
    # converting data types
    
    df['Close_date'] = pd.to_datetime(df['Close_date'], errors='coerce')
    df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')
    df['Sales_price'] = pd.to_numeric(df['Sales_price'], errors='coerce')
    df['Engage_date'] = pd.to_datetime(df['Engage_date'], errors='coerce')
    df['Close_value'] = pd.to_numeric(df['Close_value'], errors='coerce')
    df['Year_established'] = pd.to_datetime(df['Year_established'], format = '%Y')

    # Drop nan values in the 'Company_name' column
    df = df.dropna(subset = ['Company_name'])

    # Drop 'GTXPro' from the 'Product_name' column scince it has no salling price 
    df = df[df['Product_name'] != 'GTXPro']
    
    # drop the index column
    df = df.drop(columns = ['Unnamed: 0'])

    # Drop duplicates
    df = df.drop_duplicates()
    
    return df

<STRONG>EXPLORING AFTER CLEANING</STRONG>

In [21]:
file = data_cleaning('hubspot_merge_file.csv')
file.head()

,ID,Sales_agent,Product_name,Company_name,Deal_stage,Engage_date,Close_date,Close_value,sector,Year_established,Revenue,Employees,Office,Product_series,Sales_price,manager,Regional_office
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0,retail,2001-01-01,718.62,2448.0,United States,GTX,1096.0,Dustin Brinkmann,Central
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0,retail,2001-01-01,718.62,2448.0,United States,MG,55.0,Melvin Marxen,Central
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0,software,1998-01-01,2714.90,2641.0,United States,GTX,550.0,Dustin Brinkmann,Central
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0,services,1982-01-01,792.46,1299.0,United States,GTX,550.0,Summer Sewald,West
5,ZNBS69V1,Anna Snelling,MG Special,Ron-tech,Won,2016-10-29,2017-03-01,49.0,medical,1992-01-01,3922.42,6837.0,United States,MG,55.0,Dustin Brinkmann,Central

In [22]:
file.info()

<class 'pandas.DataFrame'>
Index: 6117 entries, 0 to 8791
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                6117 non-null   str
 1   Sales_agent       6117 non-null   str
 2   Product_name      6117 non-null   str
 3   Company_name      6117 non-null   str
 4   Deal_stage        6117 non-null   str
 5   Engage_date       5988 non-null   datetime64[us]
 6   Close_date        5564 non-null   datetime64[us]
 7   Close_value       5564 non-null   float64
 8   sector            6117 non-null   str
 9   Year_established  6117 non-null   datetime64[us]
 10  Revenue           6117 non-null   float64
 11  Employees         6117 non-null   float64
 12  Office            6117 non-null   str
 13  Product_series    6117 non-null   str
 14  Sales_price       6117 non-null   float64
 15  manager           6117 non-null   str
 16  Regional_office   6117 non-null   str
dtypes: datetime64[us](3), float64(4), str(10)
memory usage: 860.2 KB

<STRONG>SAVING FILE IN CSV FORMAT</STRONG>

In [ ]:
file.to_csv('hubspot_clean_file.csv', index = False)

<STRONG>CREATING CONNECTION AND EXPORTING DATA TO MYSQL WORKSPACE</STRONG>

In [ ]:
df = pd.read_csv('hubspot_clean_file.csv')
engine = create_engine("mysql+pymysql://root:naty1994@localhost:3306/sql_projects")
df.to_sql("hubspot_crm_data", con=engine, if_exists="append", index=False)

6117

<STRONG>>>>>>>................................NEXT STAGE DATA ANALYSIS USING MySql Query.............................<<<<<<<<<<</STRONG>